# Development Environment for Shelly Manager
# This docker-compose.yml is for local development with hot-reload
# For production deployment, see the examples in README.md

services:
  api:
    build:
      context: .
      dockerfile: packages/api/dev.Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      DEBUG: "true"
      SHELLY_CONFIG_FILE: "/app/config.json"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./packages/api/src:/app/packages/api/src:rw
      - ./packages/core/src:/app/packages/core/src:rw
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  web:
    build:
      context: packages/web
      dockerfile: Dockerfile
      target: builder
    environment:
      - VITE_BASE_API_URL=http://localhost:8000
    volumes:
      - ./packages/web/src:/app/src:ro
      - ./packages/web/public:/app/public:ro
      - ./packages/web/package.json:/app/package.json:ro
      - ./packages/web/vite.config.ts:/app/vite.config.ts:ro
      - ./packages/web/tsconfig.json:/app/tsconfig.json:ro
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped

  cli:
    build:
      context: .
      dockerfile: packages/cli/dev.Dockerfile
    environment:
      SHELLY_CONFIG_FILE: "/app/config.json"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./packages/cli/src:/app/packages/cli/src:rw
      - ./packages/core/src:/app/packages/core/src:rw
    profiles:
      - cli
    entrypoint: [ "tail", "-f", "/dev/null" ]
    restart: unless-stopped
