[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shelly-manager-api"
version = "0.1.0"
description = "REST API for Shelly Manager"
authors = [{name = "Jorge Lima", email = "jorgefilipemlima@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "shelly-manager-core",  # Local package dependency
    "litestar[standard]==2.16.0",
    "uvicorn[standard]==0.35.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "black",
    "ruff",
    "mypy",
]

[tool.uv.sources]
shelly-manager-core = { workspace = true }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
